### ISSUE TITLE
Cluster name parameter for install script

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#124]
## Issue Summary:
Sometimes required to use exists KIND cluster for install KNDP.
## Issue Details:
To make possible to install KNDP on existing cluster, possible to add parameter to install command, which will be used for checking if required to create cluster or use provided.
## Todo:
- [ ] Add parameter "-c|--cluster" to KNDP CLI tool.
- [ ] Add "cluster" command to help of kndp cli.
- [ ] Add command description to docs of kndp cli.
## Acceptance Criteria:
- User shall be able to set cluster name and install script shall skip cluster creation, but continue with installation of KNDP.
