### ISSUE TITLE
KNDP Command Line Interface

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#125]
## Issue Summary:
For better user experience proposed to create standalone KNDP CLI command, which help user to install and manage KNDP platform.
## Issue Details:
Create Bash based CLI tool which will have for beginning next command: help, install
## Todo:
- [ ] Create basic executable Bash script and add help command with usage display.
- [ ] Make CLI tool installable from Github URL
- [ ] Add install command which will doing installation of KNDP same like doing currently install.sh
- [ ] Add uninstall command which will remove "kndp" Kind's cluster or remove KNDP helm chart if "kndp" cluster not found.

## Acceptance Criteria:
- User shall be able to install globally to Linux KNDP CLI tool.
- On "kndp help" shall be display usage information for all commands.
- On "kndp install" shall be installed kndp platform.
- On "kndp uninstall" shall be uninstalled kndp platform.
## References:
- [CLI Guidelines](https://clig.dev/)
