### ISSUE TITLE
Platform installation give errors on helm installation

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#129]
## Issue Summary:
While testing KNP install process using CLI tool, found error which stopped install of Helm chart.
## Issue Details:
`kndp install
Git is already installed. Skipping...
Node.js is already installed. Skipping...
Docker is already installed. Skipping...
NX is already installed.
KNDP basic tools are installed.
Creating Kubernetes cluster using kind...
No kind clusters found.
Creating cluster "kndp" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼 
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-kndp"
You can now use your cluster with:

kubectl cluster-info --context kind-kndp

Have a nice day! 👋Installing Helm...
Adding kndp repository...
"kndp" already exists with the same configuration, skipping
Updating kndp repository...
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kndp" chart repository
Update Complete. ⎈Happy Helming!⎈
Installing kndp chart...
100.0% [=================================================================================================]
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "backstage-backend-app-config-cm" namespace: "" from "": no matches for kind "ConfigMap" in version "v1enabling" ensure CRDs are installed first
`
## Todo:
- [x] Fix problem.
- [x] Change "Installing kndp chart..." message to "Installing KNDP ...".
- [x] Change KNDP CLI installation command in docs: curl -sSf https://raw.githubusercontent.com/kndpio/kndp/release/0.1/scripts/install.sh | sudo sh
- [x] Change name of docs directory from /docs/kndp-cli/ to /docs/cli
- [x] Change name of docs file /docs/cli/kndp-cli.md to /docs/cli/install.md
- [x] Make /docs/cli/install.md accessible by Getting Started->Installation menu.
- [x] Remove Getting Started->Installation->KNDP for Linux page and menu.

## Acceptance Criteria:
- User shall be able to install kndp without errors.
