### ISSUE TITLE
Meal Composite Resource Definition

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#139]
## Issue Summary:
Every process in company starts from creation of topic, around what process will run and generate or update related items, which generally could/should be topics for other processes. Same for organized meal taking process. 
## Issue Details:
A fist and main step for automate process of ordering meal in office for employee, is creation of meal CRD with some properties which will be filled by controllers/bots or manually.
## Todo:
- [x] Create Crossplane Meal package.
- [x] Add to new package "Meal" Composite Resource Definition with next properties:
   - employeeRefs: array{name:string,status:string}
   - dueOrderTime: string
   - dueTakeTime: string
   - deliveryTime: string
   - status: string
 - [x] Make GitHub Action where Crossplane packages changes are detected and pushed as OCI image to kndp registry, with incremented version.

## Acceptance Criteria:
- KNDP platform user shall be able to create using k8s API to create Meal object.
## References:
- https://docs.crossplane.io/latest/concepts/composite-resource-definitions/
- https://docs.crossplane.io/latest/concepts/packages/#build-the-package

**Comment by web7evgheni** [comment]
@ca7alindev Please ask me in Slack for details, if something not clear.
