### ISSUE TITLE
Meal order request SMS sender

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#145]
## Issue Summary:
Update Meal composition function for generate Job for send SMS by TP-Link 4G router API, to restaurant number with amount of persons accepted meal.

## Todo:
- [ ] Create application in Go language for send by TL-MR6400 SMS with provided message and number.
- [ ] Pack application into OCI image.
- [ ] Update Meal composition function for create job which will send SMS to number from Helm config with message about number of meal accepted poerson.

## Acceptance Criteria:
- After dueOrdertime SMS with number of persons shall be sent automatically.
## References:
https://www.tp-link.com/uk/home-networking/3g-4g-router/tl-mr6400/
