### ISSUE TITLE
Test Meal System on local cluster

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#161]
## Issue Summary:
After everything regarding Meal system is ready, we shall install and test it.
## Issue Details:
As we have K8s machines which is usable for testing and possible production usage of Meal ordering, proposed to install and test meal system
## Todo:
- [ ] Install and configure meal system.
- [ ] Add beta testers AM and EP into slack channel.
- [ ] Test lunch ordering with beta testers.

## Acceptance Criteria:
- Users of clack channel shall be able to vote and receive request for order creation.
