### ISSUE TITLE
Implement composite resource for ActiveRelease

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#88]
## Issue Summary:
This issue entails the implementation of an ActiveRelease Custom Resource Definition (CRD) utilizing Crossplane Composition resources. Specifically, this CRD will orchestrate the creation of a Google Kubernetes Engine (GKE) node pool named after the ActiveRelease.
## Issue Details:
The goal is to leverage Crossplane's Composition framework to automate the provisioning of GKE resources tied to ActiveReleases. The CRD will contain specifications for an ActiveRelease, including the desired GKE node pool attributes.
Dependencies: Ensure that Crossplane and the necessary GCP credentials are properly configured within the Kubernetes environment.
## Todo:
- [x] Create empty Helm chart where will be store GCP related k8s resources in packages/cloud/charts/kndp-gcp.
- [x] Add GCP ProviderConfig manifest with WorkloadIdentity credentials type and service account name coming from value.
- [x] Add to Crosslane Composition implementation for ActiveRelease of releases.kndp.io/v1alpha1 API, where GKE node pool with name of release is managed by this  composition.

## Acceptance Criteria:
The "ActiveRelease" CRD is integrated into our Crossplane setup.
When an ActiveRelease resource is created, it triggers the creation of a GKE node pool with a name corresponding to the ActiveRelease.
The node pool's configuration aligns with the specifications provided in the ActiveRelease resource.
## References:
- https://docs.crossplane.io/latest/concepts/compositions/
- https://marketplace.upbound.io/providers/upbound/provider-gcp-container/v0.37.0/resources/container.gcp.upbound.io/NodePool/v1beta1
