### ISSUE TITLE
Display component's logs using Grafana Loki dashboard

### ISSUE THREAD

**Issue by web7evgheni** [kndpio/kndp#94]
## Issue Summary:
To provide better visibility into our application's logs, we aim to set up a Grafana dashboard connected to Loki, where users can filter logs based on current component tags. This will enable more efficient log monitoring and troubleshooting.
## Issue Details:
Currently, we lack a centralized and user-friendly solution for viewing application logs. Having a Grafana dashboard connected to Loki with component tags filtering will greatly enhance our ability to analyze logs in real-time.
## Todo:
- [ ] Add Grafana and Loki charts to KNDP dependencies.
- [ ] Create predefined Grafana dashboard for display Loki logs.
- [ ] Add hidden variable "app" to Grafana logs dashboard and filter logs by it.
- [ ] Create Backstage plugin for display logs of component in separate "Logs" tab using embedded version of Grafana dashboard, using dashboard URL with "app" variable equal to component name.

## Acceptance Criteria:
- After the completion of this issue, the Grafana dashboard should be set up and accessible.
- Users should be able to see logs of component in separate Logs tab.
- The dashboard should display log data from Loki in real-time.
## References:
- Loki queries: https://grafana.com/docs/loki/latest/query/log_queries/
